In [1]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
#load data
data = pd.read_excel("C:\\Users\\user\\Downloads\\iris_flask.xls")


In [3]:
#read data
data.head()

SL   SW   PL   PW Classification
0  5.1  3.5  1.4  0.2    Iris-setosa
1  4.9  3.0  1.4  0.2    Iris-setosa
2  4.7  3.2  1.3  0.2    Iris-setosa
3  4.6  3.1  1.5  0.2    Iris-setosa
4  5.0  3.6  1.4  0.2    Iris-setosa

In [4]:
#check the shape of data
data.shape

(150, 5)

In [5]:
#check the data types
data.dtypes

SL                float64
SW                float64
PL                float64
PW                float64
Classification     object
dtype: object

In [6]:
#check the columns
data.columns

Index(['SL', 'SW', 'PL', 'PW', 'Classification'], dtype='object')

In [7]:
#check null values
data.isna().sum()

SL                0
SW                0
PL                0
PW                0
Classification    0
dtype: int64

In [8]:
#to convert categorical data to numerical data
#import label encoder
from sklearn.preprocessing import LabelEncoder

In [9]:
#label_encoder=LabelEncoder()

In [10]:
#data['Classification']=label_encoder.fit_transform(data['Classification'])

In [11]:
data

SL   SW   PL   PW  Classification
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [12]:
X1=data.drop(['Classification'],axis=1)

In [13]:
X1.describe()

SL          SW          PL          PW
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.054000    3.758667    1.198667
std      0.828066    0.433594    1.764420    0.763161
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [14]:
#import minmax scaler
from sklearn.preprocessing import MinMaxScaler

In [15]:
min_max_scaler=MinMaxScaler(feature_range=(0,1))

In [16]:
X1=min_max_scaler.fit_transform(X1)

In [17]:
type(X1)

numpy.ndarray

In [18]:
X1=pd.DataFrame(X1,columns=['SL','SW','PL','PW'])

In [19]:
data1=data.drop(['SL','SW','PL','PW'],axis=1)

In [20]:
data1=pd.concat([data1,X1],axis=1)

In [21]:
data1.describe()

SL          SW          PL          PW
count  150.000000  150.000000  150.000000  150.000000
mean     0.428704    0.439167    0.467571    0.457778
std      0.230018    0.180664    0.299054    0.317984
min      0.000000    0.000000    0.000000    0.000000
25%      0.222222    0.333333    0.101695    0.083333
50%      0.416667    0.416667    0.567797    0.500000
75%      0.583333    0.541667    0.694915    0.708333
max      1.000000    1.000000    1.000000    1.000000

In [22]:
#split train and test data
X=data1.drop(['Classification'],axis=1)
y=data1['Classification']

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.2)

In [25]:
#import logistic regression
from sklearn.linear_model import LogisticRegression
lor=LogisticRegression()
lor_model=lor.fit(X_train,y_train)
y_predict_lor=lor_model.predict(X_test)

In [26]:
#import confusion matrix
from sklearn.metrics import confusion_matrix

In [27]:
#confusion matrix
confusion_matrix(y_test,y_predict_lor)

array([[10,  0,  0],
       [ 0,  8,  1],
       [ 0,  0, 11]], dtype=int64)

In [28]:
#import precision score and recall score
from sklearn.metrics import precision_score,recall_score

In [29]:
#precision score
precision_score(y_test,y_predict_lor,pos_label=1,average='micro')


0.9666666666666667

In [30]:
#recallscore
recall_score(y_test,y_predict_lor,pos_label=1,average='micro')

0.9666666666666667

In [31]:
#check accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_predict_lor)

0.9666666666666667

In [32]:
#import KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier

In [33]:
metric_k=[]
neighbors=range(3,20)
for k in neighbors:
  classifier= KNeighborsClassifier(n_neighbors=k)
  classifier=classifier.fit(X_train,y_train)
  y_pred_kNN=classifier.predict(X_test)
  acc=accuracy_score(y_test,y_pred_kNN)
  metric_k.append(acc)

In [34]:
#print metric 
metric_k


[1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0]

In [35]:
classifier= KNeighborsClassifier(n_neighbors=5)
classifier=classifier.fit(X_train,y_train)
y_pred_kNN=classifier.predict(X_test)

In [36]:
#find confusion matrix
confusion_matrix(y_test,y_pred_kNN)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]], dtype=int64)

In [37]:
#find precision score
precision_score(y_test,y_pred_kNN,pos_label=1,average='micro')

1.0

In [38]:
#find recall score
recall_score(y_test,y_pred_kNN,pos_label=1,average='micro')

1.0

In [39]:
#find accuracy score
accuracy_score(y_test,y_pred_kNN)

1.0

In [40]:
#import Support Vector Classification
from sklearn.svm import SVC

In [41]:
svm_clf=SVC(kernel='linear')
svm_clf=svm_clf.fit(X_train,y_train)
y_pred_svm=svm_clf.predict(X_test)

In [42]:
#find confusion_matrix
confusion_matrix(y_test,y_pred_svm)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]], dtype=int64)

In [43]:
#find precision score
precision_score(y_test,y_pred_svm,pos_label=1,average='micro')

1.0

In [44]:
#find recall score
recall_score(y_test,y_pred_svm,pos_label=1,average='micro')

1.0

In [45]:
#find accuracy score
accuracy_score(y_test,y_pred_svm)

1.0

In [46]:
svm_clf2=SVC(kernel='rbf')
svm_clf2=svm_clf2.fit(X_train,y_train)
y_pred_svm2=svm_clf2.predict(X_test)

In [47]:
#find confusion_matrix
confusion_matrix(y_test,y_pred_svm2)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]], dtype=int64)

In [48]:
#find precision score
precision_score(y_test,y_pred_svm2,pos_label=1,average='micro')

1.0

In [49]:
#find recall score
recall_score(y_test,y_pred_svm2,pos_label=1,average='micro')

1.0

In [50]:
#find accuracy score
accuracy_score(y_test,y_pred_svm2)

1.0

In [51]:
#import decision tree
from sklearn.tree import DecisionTreeClassifier

In [52]:
model= DecisionTreeClassifier()
model=model.fit(X_train,y_train)
y_pred_dt=model.predict(X_test)

In [53]:
#find confusion matrix
confusion_matrix(y_test,y_pred_dt)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]], dtype=int64)

In [54]:
#find precision score
precision_score(y_test,y_pred_dt,pos_label=1,average='micro')

1.0

In [55]:
#find recall score
recall_score(y_test,y_pred_dt,pos_label=1,average='micro')

1.0

In [56]:
#find accuracy score
accuracy_score(y_test,y_pred_dt)

1.0

In [57]:
#import random forest classifier
from sklearn.ensemble import RandomForestClassifier

In [58]:
rf_clf=RandomForestClassifier()
rf_clf=rf_clf.fit(X_train,y_train)
y_pred_rf=rf_clf.predict(X_test)

In [59]:
#find confusion matrix
confusion_matrix(y_test,y_pred_rf)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]], dtype=int64)

In [60]:
#find precision score
precision_score(y_test,y_pred_rf,pos_label=1,average='micro')

1.0

In [61]:
#find recall score
recall_score(y_test,y_pred_rf,pos_label=1,average='micro')

1.0

In [62]:
#find accuracy score
accuracy_score(y_test,y_pred_rf)

1.0

In [63]:
# save the model
import pickle
filename = 'model.pkl'
pickle.dump(model, open(filename, 'wb'))

In [64]:
X_test.head()

SL        SW        PL        PW
73   0.500000  0.333333  0.627119  0.458333
18   0.388889  0.750000  0.118644  0.083333
118  0.944444  0.250000  1.000000  0.916667
78   0.472222  0.375000  0.593220  0.583333
76   0.694444  0.333333  0.644068  0.541667

In [65]:
load_model = pickle.load(open(filename,'rb'))

In [66]:
load_model.predict([[0.500000,0.333333,0.627119,0.458333]])

array(['Iris-versicolor'], dtype=object)